// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           53
// Async Callback:                       1
// Total number of exported functions:  55

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    onedex_sc
    (
        setConfig
        setTotalFeePercent
        setSpecialFeePercent
        setStakingRewardFeePercent
        setStakingRewardAddress
        setTreasuryAddress
        setBurnerAddress
        setUnwrapAddress
        setRegisteringCost
        getWegldTokenId
        getUsdcTokenId
        getBusdTokenId
        getUsdtTokenId
        getTotalFeePercent
        getSpecialFeePercent
        getStakingRewardFeePercent
        getTreasuryAddreess
        getStakingRewardAddress
        getBurnerAddreess
        getUnwrapAddreess
        getRegisteringCost
        getPaused
        getPairIds
        getLastPairId
        getLpTokenPairIdMap
        getPairOwner
        getPairState
        getPairEnabled
        getPairFirstTokenId
        getPairSecondTokenId
        getPairFirstTokenReserve
        getPairSecondTokenReserve
        getPairLpTokenId
        getPairLpTokenTotalSupply
        enableSwap
        createPair
        issueLpToken
        setLpTokenLocalRoles
        setPairActive
        setPairActiveButNoSwap
        setPairInactive
        addInitialLiquidity
        addLiquidity
        removeLiquidity
        swapMultiTokensFixedInput
        swapMultiTokensFixedOutput
        getEquivalent
        getMultiPathAmountOut
        getAmountOut
        getMultiPathAmountIn
        getAmountIn
        viewPairs
        viewPair
        callBack
    )
}
